BOT_TOKEN: 
  - MTA2MjU5MjQ2MTQ1MDUyNjg4MQ.GY0Nrg.v6OwW4N04ub6Z07ZSFpOAKhTKDte_uUezx6qEY
  
CHANNEL_ID: 
  - 1043951285088567357

MODE: quote
REPLY: 
SIMSIMI_LANG: id
DELAY: 5
DEL_AFTER: 3
REPOST_LAST_CHAT: 0
